apiVersion: ako.vmware.com/v1alpha1
kind: HostRule
metadata:
  name: {{ .Values.name }}
spec:
  virtualhost:
    fqdn: {{ .Values.name }}.{{ .Values.domain }}
    enableVirtualHost: true
    wafPolicy: System-WAF-Policy
    tls: # optional
      sslKeyCertificate:
        name: System-Default-Cert-EC
        type: ref
    analyticsPolicy: # optional
      fullClientLogs:
        enabled: true
        throttle: HIGH
      logAllHeaders: true
